import { getHostPlatform } from './host';
import { shortcutLabel } from './shortcuts';

export type Language = 'en' | 'tr';

const en = {
  menuFile: 'File', menuEdit: 'Edit', menuView: 'View', menuRun: 'Run', menuHelp: 'Help',
  appMenu: 'Application menu',
  openProject: 'Open Project', newProject: 'New Project', save: 'Save', build: 'Build', run: 'Run', stop: 'Stop',
  saveTitle: 'Save (Ctrl+S)', buildTitle: 'Build (Ctrl+Shift+B)', runTitle: 'Build and Run (F5)',
  stopTitle: 'Stop (Shift+F5)', settings: 'Settings', explorer: 'EXPLORER',
  buildRunControls: 'Build and run controls',
  newFile: 'New File', newFolder: 'New Folder', newCppClass: 'New C++ Class',
  newMenu: 'New', copy: 'Copy', paste: 'Paste', showIn: 'Show in',
  systemExplorer: 'System Explorer', commandPrompt: 'CMD',
  copied: 'Copied', pasted: 'Pasted', copyFailed: 'Could not copy item', showFailed: 'Could not open location',
  rename: 'Rename', delete: 'Move to Recycle Bin', deleteTitle: 'Move Selected Item to Recycle Bin',
  refresh: 'Refresh', projectPlaceholder: 'GLIST PROJECT', noFolder: 'No folder is open.',
  noFolderHint: 'Open an existing Glist project or create a new one.',
  openFolder: 'Open Folder', tagline: 'A focused development environment for Glist Engine.',
  output: 'OUTPUT', ready: 'Ready', clearOutput: 'Clear Output',
  closeExplorer: 'Close Explorer', closeOutput: 'Close Panel',
  terminal: 'TERMINAL', newTerminal: 'New Terminal', clearTerminal: 'Clear Terminal',
  dependencies: 'DEPENDENCIES',
  engineMissing: 'GlistEngine was not found two folders above the project, where the build looks for it.',
  pluginMissing: 'This plugin is named in CMakeLists.txt but is not in glistplugins, so the build will stop. Plugins can be downloaded from github.com/GlistPlugins.',
  agentTab: 'AGENT', restartAgent: 'Restart the Agent', clearAgent: 'Clear', agentChoice: 'Agent',
  agentExited: 'The agent exited with code', showAgent: 'Show Agent', hideAgent: 'Hide Agent',
  agents: 'Agents', agentInstall: 'Install', agentInstalling: 'Installing...', agentNotInstalled: 'Not installed',
  agentFromStudio: 'Installed in the Glist folder', agentFromGlist: 'Comes with Glist',
  agentFromSystem: 'Installed on this computer',
  agentInstallYourself: 'Not installed. Its own installer sets it up for the whole computer.',
  agentsHint: 'Coding assistants that work in the Agent tab, in the open project. Turn on the ones you want. One that is not installed can be installed here: it goes into the Glist folder, and nothing else on the computer changes.',
  terminalExited: 'The shell exited with code', terminalRestartHint: 'Press any key to start a new one.',
  initialOutput: 'Glist Studio is ready. Open a project to get started.',
  cancel: 'Cancel', create: 'Create', close: 'Close', template: 'Template',
  searchProjects: 'Search projects', browse: 'Browse...', neverOpened: 'Not opened yet', lastOpened: 'Opened {time}',
  noProjects: 'No projects here yet. Make one with New Project, or browse for a folder.',
  projectName: 'Project name', language: 'Language', appearance: 'Appearance',
  importTheme: 'Import a Theme File...', removeTheme: 'Remove',
  fonts: 'Fonts', codeFont: 'Code font', codeFontSize: 'Code size', interfaceFont: 'Interface font', systemFont: 'System',
  ligatures: 'Join characters such as => where the font supports it',
  fontsHint: 'Pick a font from the list or type the name of one installed on this computer.',
  pathSettings: 'PATH',
  pathHint: 'The folders builds, runs, the debugger and the terminal look in for programs and DLLs, in this order. Glist Studio gives them its own list rather than the computer\'s PATH: Glist\'s tools, the system\'s folders and the plugins\' DLLs, which cannot be changed here. Folders added here come last.',
  pathGlist: 'Glist tools', pathCmake: 'CMake', pathSystem: 'This computer', pathGit: 'Git', pathPlugin: '{name} plugin', pathCustom: 'Added here',
  addPathFolder: 'Add Folder...', removePathFolder: 'Remove', pathMissing: 'This folder does not exist.',
  pathInvalid: 'This folder cannot be added.',
  pageGeneral: 'General', pageAppearance: 'Appearance', pageBuild: 'Build', pageRun: 'Run and Debug',
  pageEnvironment: 'Environment', pageGit: 'Git', pageAgents: 'Agents', pageAbout: 'About',
  macServices: 'Services', macHide: 'Hide Glist Studio', macHideOthers: 'Hide Others', macShowAll: 'Show All',
  macQuit: 'Quit Glist Studio', macWindow: 'Window', selectAll: 'Select All',
  aboutMenu: 'About Glist Studio', aboutVersion: 'Version', aboutCommit: 'Commit', aboutBranch: 'Branch', aboutFolder: 'Folder',
  aboutNoBranch: 'None, a commit is checked out', aboutNotGit: 'Not a Git checkout', aboutNotFound: 'Not found',
  aboutUnknown: 'Unknown', aboutPlugins: 'Plugins of the open project', aboutSystem: 'System', aboutCopy: 'Copy All',
  aboutCopied: 'Copied to the clipboard.', aboutHint: 'When you report a problem, Copy All and paste it into the report.',
  runSettings: 'Run', runArguments: 'Program arguments',
  runArgumentsHint: 'Given to {project}\'s program when Run or Debug starts it. An argument with spaces goes in quotes.',
  runArgumentsNoProject: 'Open a project to give its program arguments.',
  envSettings: 'Environment Variables', envName: 'Name', envValue: 'Value', addVariable: 'Add Variable',
  envHint: 'Set for builds, runs, the debugger and the terminal, in every project. PATH has its own list above.',
  envInvalid: 'A name is letters, digits and underscores, not starting with a digit. PATH has its own list above.',
  themeImportFailed: 'This file is not a VS Code color theme.',
  languageHint: 'The interface language changes immediately.',
  editorLanguageRestart: 'The editor\'s find box and its own commands in the palette change language when Glist Studio starts again.',
  themeHint: 'Themes color the whole studio. Color themes from VS Code (.json) can be imported.',
  undo: 'Undo', redo: 'Redo', find: 'Find', showExplorer: 'Show Explorer', hideExplorer: 'Hide Explorer',
  showOutput: 'Show Output', hideOutput: 'Hide Output', showTerminal: 'Show Terminal', hideTerminal: 'Hide Terminal', engineAbout: 'About Glist Engine',
  installGlist: 'Install Glist Engine', installGlistMenu: 'Install Glist Engine...', tryAgain: 'Try Again', stopInstall: 'Stop',
  checkForUpdates: 'Check for Updates...', updateSettings: 'Updates', autoUpdate: 'Download new versions automatically',
  autoUpdateHint: 'New versions come from Glist Studio\'s releases on GitHub. One that has been downloaded is installed when Glist Studio restarts.',
  updatePreviews: 'Get previews too', updatePreviewsHint: 'Previews are built from every change to Glist Studio, before a release: the newest work, less tested.',
  updateReady: 'Glist Studio {version} is ready to install.', restartToUpdate: 'Restart to Update',
  updateAvailable: 'Glist Studio {version} is out.', updateDownload: 'Download', upToDate: 'Glist Studio is up to date.',
  updateDownloading: 'Downloading Glist Studio {version}...', updateFailed: 'Could not check for updates',
  openGlistApp: 'Open GlistApp', glistMissing: 'Glist Engine is not installed on this computer yet.',
  glistInstallIntro: 'This runs Glist Engine\'s own installer, the current one from github.com/GlistEngine/InstallScripts. It installs the compilers and libraries Glist needs, and puts the engine, an example app and the Glist tools in this folder. It downloads 1 to 2 GB.',
  installPasswordSystem: 'If it needs this computer\'s password, the system asks for it in a window of its own; Glist Studio never sees it.',
  installPasswordTerminal: 'If it needs this computer\'s password, type it in the terminal that appears below.',
  installStep: 'Step {step} of {total}: {name}', installStarting: 'Starting the installer...',
  glistInstalled: 'Glist Engine is installed.', glistInstallFailed: 'The installation stopped', exitCode: 'exit code',
  installStopped: 'stopped', confirmStopInstall: 'Stop the installation? What it has done so far stays, and installing again continues from there.',
  layout: 'Layout', zoom: 'Zoom', preferences: 'Preferences',
  zoomIn: 'Zoom In', zoomOut: 'Zoom Out', resetZoom: 'Reset Zoom',
  scale: 'Scale', scaleReset: 'Back to 100%', zoomInTitle: 'Zoom In (Ctrl++)', zoomOutTitle: 'Zoom Out (Ctrl+-)',
  resetZoomTitle: 'Back to 100% (Ctrl+0)',
  scaleHint: 'Makes everything in the studio larger or smaller, for example on a classroom projector.',
  fileName: 'File name', folderName: 'Folder name', className: 'Class name', newName: 'New name',
  openedProject: 'Project', noCmake: 'CMakeLists.txt was not found in this folder.',
  fileCreated: 'File created', folderCreated: 'Folder created', classCreated: 'C++ class created',
  projectCreated: 'Project created', movedToTrash: 'Moved to Recycle Bin', renamed: 'Renamed',
  renamedTo: '{from} is now {to}', goToError: 'Go to Error',
  createFailed: 'Could not create item', deleteFailed: 'Could not delete item', renameFailed: 'Could not rename item',
  fileOpenFailed: 'Could not open file', projectOpenFailed: 'Could not open project', treeFailed: 'Could not load files', saveFailed: 'Save failed',
  saved: 'saved', buildSucceeded: 'Build succeeded', buildFailed: 'Build failed',
  running: 'Application running', exit: 'Exit',
  confirmProjectSwitch: 'You have unsaved files. Open another project?',
  confirmClose: 'has unsaved changes. Close anyway?',
  confirmDeleteFile: 'Move this file to the Recycle Bin?',
  confirmDeleteFolder: 'Move this folder and all its contents to the Recycle Bin?',
  confirmDirtyDelete: 'Unsaved changes in this item will be lost. Continue?',
  classLocation: 'Select a folder for the C++ class.',
  open: 'Open',
  readOnly: 'Read-only', switchSourceHeader: 'Switch Header/Source', clangdRunning: 'is running',
  closeOthers: 'Close Others', closeAll: 'Close All', splitRight: 'Split Right', splitLeft: 'Split Left',
  moveRight: 'Move to the Right Side', moveLeft: 'Move to the Left Side', splitEditor: 'Split Editor Right',
  goToDefinition: 'Go to Definition', goToDeclaration: 'Go to Declaration', goToReferences: 'Go to References',
  goToSymbol: 'Go to Symbol...', peek: 'Peek', peekDefinition: 'Peek Definition', peekDeclaration: 'Peek Declaration',
  peekReferences: 'Peek References', renameSymbol: 'Rename Symbol', changeAllOccurrences: 'Change All Occurrences',
  formatDocument: 'Format Document', formatSelection: 'Format Selection', cut: 'Cut',
  commandPalette: 'Command Palette', paletteSearch: 'Type a command', paletteEmpty: 'No command matches.', editorCommands: 'Editor',
  renameUnavailable: 'This symbol cannot be renamed.',
  editOutsideProject: 'The change touches files outside the project and was not applied.',
  debug: 'Debug', debugTitle: 'Debug (F6)', debugView: 'Run and Debug', startDebugging: 'Start Debugging',
  continue: 'Continue', continueTitle: 'Continue (F5)', pause: 'Pause',
  stepOver: 'Step Over', stepOverTitle: 'Step Over (F10)', stepInto: 'Step Into', stepIntoTitle: 'Step Into (F11)',
  stepOut: 'Step Out', stepOutTitle: 'Step Out (Shift+F11)', toggleBreakpoint: 'Toggle Breakpoint',
  breakpoint: 'Breakpoint', removeBreakpoint: 'Remove breakpoint',
  runAndDebug: 'RUN AND DEBUG', variables: 'VARIABLES', callStack: 'CALL STACK', breakpoints: 'BREAKPOINTS',
  noBreakpoints: 'Click to the left of a line number to stop there while debugging.',
  debugIdle: 'Debug runs your app so you can pause it, look at its variables, and go line by line.',
  debugStarting: 'Building for debugging and starting the debugger...',
  debugRunning: 'Running', debugPaused: 'Paused',
  programExited: 'The program exited with code', debuggerFailed: 'The debugger could not be started',
  debuggerSettings: 'Debugger', installDebugger: 'Install GDB',
  debuggerInstalledText: '{name} {version}, from MSYS2, is installed for debugging.',
  debuggerNotInstalled: 'Glist\'s tools have no debugger on Windows. Glist Studio can install {name} from MSYS2, the source of Glist\'s compilers, with every file checked against a pinned checksum ({size}).',
  installingDebugger: 'Installing GDB... {percent}%', debuggerReady: 'GDB is installed. Press Debug to start.',
  debuggerInstallFailed: 'GDB could not be installed', debuggerMissingNotice: 'There is no debugger yet.',
  debuggerFailedNotice: 'GDB could not start. Installing it again usually fixes that.', installDebuggerAgain: 'Install GDB Again',
  gitSettings: 'Git',
  gitEnable: 'Show Git tools',
  gitHint: 'Adds a Commit view beside the explorer, a Git tab below the editor and the current branch to the title bar, and marks changed lines beside the line numbers. Projects stay as they are until you use them.',
  gitFound: 'Git {version} is installed.',
  gitNotFound: 'Git was not found on this computer. Install it from git-scm.com, then open Settings again.',
  gitName: 'Your name',
  gitEmail: 'Email',
  gitIdentityHint: 'Commits are signed with these, in every project on this computer.',
  gitUpdateMethod: 'Update Project brings in commits from the remote by',
  gitUpdateMerge: 'Merging them into the branch',
  gitUpdateRebase: 'Putting the branch\'s own commits after them (rebase)',
  gitProtect: 'Protect pushed commits',
  gitProtectHint: 'A commit that is already pushed cannot be amended, and protected branches cannot be force pushed, so nobody rewrites history others already have.',
  gitProtectedBranches: 'Protected branches',
  gitProtectedHint: 'Separated by commas; * stands for any text, as in release/*. Branches GitHub protects are protected too.',
  amendLocked: 'The last commit is already pushed, so it cannot be amended.',
  forcePushLocked: '{branch} is protected, so it is never overwritten.',
  commitView: 'COMMIT',
  commitViewTitle: 'Commit (Ctrl+K)',
  changes: 'Changes',
  unversioned: 'Unversioned Files',
  mergeConflicts: 'Merge Conflicts',
  noChanges: 'No changes since the last commit.',
  commitMessage: 'Commit message',
  commitMessageHint: 'What changed, and why (Ctrl+Enter commits)',
  amend: 'Amend the last commit',
  commit: 'Commit',
  commitAndPush: 'Commit and Push...',
  rollback: 'Rollback',
  rollbackTitle: 'Rollback Checked Files',
  confirmRollback: 'Put {count} files back as they were in the last commit? Your changes to them will be lost. Files that are new go to the trash.',
  confirmRollbackOne: 'Put {name} back as it was in the last commit? Your changes to it will be lost.',
  showDiff: 'Show Diff',
  openFile: 'Open File',
  addToGitignore: 'Add to .gitignore',
  showHistory: 'Show History',
  markResolved: 'Mark as Resolved',
  keepMine: 'Keep Mine',
  takeTheirs: 'Take Theirs',
  keepBoth: 'Keep Both',
  conflictHint: 'Open a file to choose change by change, or keep one side for the whole file.',
  noRepository: 'This project does not keep its history with Git yet.',
  noRepositoryHint: 'With a repository, you save versions of the project as commits, can go back to any of them, and can share the project.',
  pluginsView: 'Plugins', pluginsTitle: 'PLUGINS', pluginsSearch: 'Search plugins',
  pluginsInstalled: 'Installed', pluginsAvailable: 'Available',
  updateAskTitle: 'Update {name}?',
  updateAskHint: '{source} has new commits, and {name} has work of yours: {work}.',
  updateWorkFile: '1 changed file', updateWorkFiles: '{count} changed files',
  updateWorkCommit: '1 commit of your own', updateWorkCommits: '{count} commits of your own', updateWorkAnd: ' and ',
  updateKeepFiles: 'Keep my changes: bring in the new commits, then put my changed files back',
  updateKeepRebase: 'Keep my work: put my commits on top of the new ones',
  updateKeepMerge: 'Keep my work: merge the new commits with mine',
  updateKeepMergeWhy: 'Yours are on {branch}, which is protected, so they are merged rather than rewritten.',
  updateKeepRebasePushed: 'Yours are on {branch} already; after this, sending them there again needs a force push.',
  updateReplace: 'Use the version on {source}: my commits stay on a branch of their own, my changed files in Stashes',
  updateReplaceFiles: 'Use the version on {source}: my changed files go to Stashes',
  updateReplaceCommits: 'Use the version on {source}: my commits stay on a branch of their own',
  updateButton: 'Update', updateUpToDate: '{name} is up to date with {source}.',
  updateDoneFastForward: '{name} is updated from {source}.',
  updateDoneRebase: '{name} is updated from {source}, with your commits on top.',
  updateDoneMerge: '{name} is updated from {source}, merged with your commits.',
  updateDoneReplace: '{name} now matches {source}.',
  updateKeptStash: 'Your changed files are in Stashes as "{stash}".', updateKeptBranch: 'Your commits are on the branch {branch}.',
  updateStashClash: 'Your changed files clash with the new version, so they wait in Stashes, in the Git tab.',
  updateNothingChanged: 'Nothing was changed.', updateUseSource: 'Use the Version on {source}', updateResolve: 'Resolve Conflicts',
  checkoutUpdateFailed: '{name} could not be updated', updatesNotice: 'New versions of {names}',
  dependenciesUpToDate: 'Up to date: {names}',
  installPlugin: 'Install', updatePlugin: 'Update', addToProject: 'Add to Project', removeFromProject: 'Remove from Project',
  installPluginTitle: 'Install into glistplugins', updatePluginTitle: 'Update from {source}',
  pluginAdd: 'Add', pluginAdded: 'Added', pluginRemove: 'Remove',
  pluginBehind: '{count} new on {source}', pluginNotOfficial: 'Not from {source}',
  pluginOtherBranch: 'On {branch}', pluginChanged: 'Changes of yours', pluginWorking: 'Working...',
  pluginInstalled: '{name} is installed in glistplugins.', pluginInstallFailed: '{name} could not be installed',
  pluginUseFailed: '{name} could not be added to the project',



  pluginFrom: 'From {source}',
  pluginsNeedGit: 'Installing and updating plugins needs Git. Install it from git-scm.com.',
  pluginsListFailed: 'GlistPlugins could not be reached',
  createRepository: 'Create Git Repository',
  gitNoProject: 'Open a project to see its changes.',
  gitMissing: 'Git was not found on this computer. Install it from git-scm.com.',
  repositoryAt: 'Repository: {location}',
  merging: 'Merging: {subject}',
  rebasing: 'Rebasing {subject}',
  cherryPicking: 'Cherry-picking {subject}',
  reverting: 'Reverting {subject}',
  resolveThenCommit: 'Resolve the conflicts, then commit.',
  resolveThenContinue: 'Resolve the conflicts, then continue.',
  abort: 'Abort',
  skip: 'Skip',
  updateProject: 'Update Project',
  updateProjectTitle: 'Update Project (Ctrl+T)',
  push: 'Push...',
  pushTitle: 'Push (Ctrl+Shift+K)',
  fetch: 'Fetch',
  committedMessage: 'Committed: {subject}',
  stateModified: 'Modified',
  stateAdded: 'Added',
  stateDeleted: 'Deleted',
  stateRenamed: 'Renamed',
  stateUntracked: 'Unversioned',
  stateConflict: 'Conflict',
  stateTypechange: 'Type changed',
  stateIgnored: 'Ignored by Git',
  diffHead: 'Last commit ({hash})',
  diffWorking: 'Your version',
  diffCommit: 'Commit {hash}',
  diffMissing: 'Not in this version',
  diffBinary: 'This file is not text, so there are no lines to compare.',
  diffTooLarge: 'This file is too large to compare.',
  previousChange: 'Previous Change',
  nextChange: 'Next Change',
  toggleSideBySide: 'Side by Side or One Column',
  gitTab: 'GIT',
  gitLog: 'Log',
  gitBranches: 'Branches',
  gitRemotes: 'Remotes',
  gitStashes: 'Stashes',
  gitConsole: 'Console',
  allBranches: 'All branches',
  searchCommits: 'Search messages or hashes',
  historyOf: 'History of {name}',
  clearFilter: 'Show all history',
  noCommits: 'No commits yet.',
  selectCommit: 'Select a commit to see what it changed.',
  copyHash: 'Copy Revision Number',
  checkoutRevision: 'Checkout Revision',
  newBranch: 'New Branch...',
  newTag: 'New Tag...',
  cherryPick: 'Cherry-Pick',
  revertCommit: 'Revert Commit',
  resetHere: 'Reset Current Branch to Here...',
  resetTitle: 'Reset {branch} to {hash}',
  resetMixed: 'Keep the changes of the later commits, as changes not committed yet',
  resetSoft: 'Keep them, ready to be committed again',
  resetHard: 'Throw away the later commits and every change not committed',
  reset: 'Reset',
  confirmResetHard: 'Throw away the later commits and all changes not committed? This cannot be undone.',
  local: 'Local',
  remote: 'Remote',
  tags: 'Tags',
  checkout: 'Checkout',
  mergeInto: 'Merge into {branch}',
  rebaseOnto: 'Rebase {branch} onto This',
  deleteBranch: 'Delete',
  currentBranch: 'current',
  branchGone: 'gone from the remote',
  confirmDeleteBranch: 'Delete the branch {name}?',
  confirmForceDelete: '{name} has commits that are in no other branch. Delete it anyway? They will be lost.',
  confirmDeleteRemoteBranch: 'Delete {name} from the remote? Everyone using it loses it.',
  confirmDeleteTag: 'Delete the tag {name}?',
  branchName: 'Branch name',
  newBranchFrom: 'New branch from {start}',
  tagName: 'Tag name',
  tagMessage: 'Message (optional)',
  addRemote: 'Add Remote...',
  remoteName: 'Name',
  remoteUrl: 'URL',
  editRemote: 'Edit URL...',
  removeRemote: 'Remove',
  confirmRemoveRemote: 'Remove the remote {name} from this repository? Nothing on the remote itself is deleted.',
  noRemotes: 'No remotes yet. Add one to push the project somewhere, such as GitHub.',
  stashChanges: 'Stash Changes...',
  stashMessage: 'Message (optional)',
  stashUntracked: 'Include unversioned files',
  applyStash: 'Apply',
  popStash: 'Apply and Delete',
  dropStash: 'Delete',
  confirmDropStash: 'Delete {name}? The changes in it will be lost.',
  noStashes: 'Nothing is stashed. Stashing puts your changes aside, so you can work on something else and bring them back later.',
  clearConsole: 'Clear Console',
  gitRefresh: 'Refresh',
  pushCommits: 'Push Commits',
  pushTarget: '{branch} to {remote}',
  pushNothing: 'There are no commits to push.',
  pushNewBranch: 'The branch is new on the remote, and will follow it from now on.',
  pushTags: 'Push tags too',
  forcePush: 'Overwrite the remote branch (force push)',
  forcePushHint: 'Only for commits that were changed after they were pushed. Commits others pushed since would be lost.',
  pushButton: 'Push',
  remoteLabel: 'Remote',
  cloneMenu: 'Get from Git...',
  cloneTitle: 'Get from Git',
  cloneUrl: 'Repository URL',
  cloneLocation: 'It goes into {location}.',
  cloneButton: 'Clone',
  cloning: 'Cloning...',
  identityTitle: 'Who is committing?',
  identityHint: 'Git records a name and an email with each commit. They are kept for every project on this computer, and can be changed in Settings.',
  saveButton: 'Save',
  menuGit: 'Git',
  commitMenu: 'Commit...',
  pushMenu: 'Push...',
  branchesMenu: 'Branches...',
  gitLogMenu: 'Show Git Log',
  remotesMenu: 'Manage Remotes...',
  currentFile: 'Current File',
  annotate: 'Annotate with Git Blame',
  hideAnnotate: 'Close Annotations',
  localBranches: 'Local Branches',
  remoteBranches: 'Remote Branches',
  manageBranches: 'Manage Branches...',
  detached: 'Detached at {hash}',
  branchChipTitle: 'Git branch: {branch}',
  aheadBehind: '{ahead} to push, {behind} to update',
  pushedTo: 'Pushed to {target}.',
  updatedFrom: 'Updated from {upstream}.',
  fetched: 'Fetched.',
  checkedOut: 'Checked out {name}.',
  smartCheckout: 'Stash and Checkout',
  conflictsNotice: 'There are conflicts to resolve. They are listed in the Commit view.',
  showConflicts: 'Show',
  showConsole: 'Show Console',
  deleteAnyway: 'Delete Anyway',
  gitFailed: 'Git could not do this',
  committing: 'Committing...',
  pushing: 'Pushing...',
  updating: 'Updating...',
  fetching: 'Fetching...',
  gitWorking: 'Working...',
  rollbackChange: 'Rollback This Change',
  linesBefore: 'Before this change',
  linesAdded: 'These lines are new since the last commit.',
  notCommittedYet: 'Not committed yet',
  blameUnavailable: 'This file has no committed history yet.',
  mine: 'Mine',
  theirs: 'Theirs',
  showInLog: 'Show in Git Log',
  blameClick: 'Click the line number to show the commit in the Git log.',
  conflictsResolvedIn: 'Every conflict in {name} is resolved.',
  keptMine: '{name}: your version was kept.',
  confirmShared: '{name} is shared by every project that uses it, so this changes it for all of them. Continue?',
  engineAndPlugins: 'Engine and Plugins',
  updateDependencies: 'Update Engine and Plugins',
  confirmUpdateDependencies: 'Bring in the latest commits of {names} from where they are published? Every project that uses them gets the changes.',
  kindProject: 'project',
  kindEngine: 'engine',
  kindPlugin: 'plugin',
  repositoryChoice: 'Repository',
  pushedRepository: '{name}: pushed to {target}.',
  sharedChanges: 'Changes in {name}, which every project that uses it shares. They are committed to its own repository.',
  sharedEdit: '{name} is shared by every project that uses it, so saving changes it for all of them.',
  tookTheirs: '{name}: their version was taken.',
  buildSettings: 'Build',
  autoConfigure: 'Configure again when CMake files change',
  autoConfigureHint: 'When CMakeLists.txt or another CMake file of the project, the engine or its plugins changes, CMake configures the project again a moment later, so code completion knows new files without a build.',
  showTargets: 'Show all targets',
  showTargetsHint: 'Adds a list beside Run of every target CMake builds, the engine\'s and plugins\' too, as CLion has. Build, Run and Debug then use the one chosen.',
  targetChoice: 'Target to build and run', targetLibrary: 'library', targetStep: 'build step',
  noTargets: 'No targets yet: build once', otherTargets: 'Other',
} as const;

export type TranslationKey = keyof typeof en;

const tr: Record<TranslationKey, string> = {
  menuFile: 'Dosya', menuEdit: 'Düzen', menuView: 'Görünüm', menuRun: 'Çalıştır', menuHelp: 'Yardım',
  appMenu: 'Uygulama menüsü',
  openProject: 'Proje Aç', newProject: 'Yeni Proje', save: 'Kaydet', build: 'Derle', run: 'Çalıştır', stop: 'Durdur',
  saveTitle: 'Kaydet (Ctrl+S)', buildTitle: 'Derle (Ctrl+Shift+B)', runTitle: 'Derle ve Çalıştır (F5)',
  stopTitle: 'Durdur (Shift+F5)', settings: 'Ayarlar', explorer: 'GEZGİN',
  buildRunControls: 'Derleme ve çalıştırma kontrolleri',
  newFile: 'Yeni Dosya', newFolder: 'Yeni Klasör', newCppClass: 'Yeni C++ Sınıfı',
  newMenu: 'Yeni', copy: 'Kopyala', paste: 'Yapıştır', showIn: 'Konumu Aç',
  systemExplorer: 'Dosya Gezgini', commandPrompt: 'CMD',
  copied: 'Kopyalandı', pasted: 'Yapıştırıldı', copyFailed: 'Öğe kopyalanamadı', showFailed: 'Konum açılamadı',
  rename: 'Yeniden Adlandır', delete: 'Geri Dönüşüm Kutusu’na Taşı', deleteTitle: 'Seçili Öğeyi Geri Dönüşüm Kutusu’na Taşı',
  refresh: 'Yenile', projectPlaceholder: 'GLIST PROJESİ', noFolder: 'Açık klasör yok.',
  noFolderHint: 'Var olan bir Glist projesini açın ya da yenisini oluşturun.',
  openFolder: 'Klasör Aç', tagline: 'Glist Engine için yalın bir geliştirme ortamı.',
  output: 'ÇIKTI', ready: 'Hazır', clearOutput: 'Çıktıyı Temizle',
  closeExplorer: 'Gezgini Kapat', closeOutput: 'Paneli Kapat',
  terminal: 'TERMİNAL', newTerminal: 'Yeni Terminal', clearTerminal: 'Terminali Temizle',
  dependencies: 'BAĞIMLILIKLAR',
  engineMissing: 'GlistEngine, projenin iki klasör yukarısında bulunamadı; derleme onu orada arar.',
  pluginMissing: 'Bu eklentinin adı CMakeLists.txt dosyasında geçiyor ama eklenti glistplugins klasöründe yok; bu yüzden derleme durur. Eklentiler github.com/GlistPlugins adresinden indirilebilir.',
  agentTab: 'AJAN', restartAgent: 'Ajanı Yeniden Başlat', clearAgent: 'Temizle', agentChoice: 'Ajan',
  agentExited: 'Ajan kapandı, çıkış kodu:', showAgent: 'Ajanı Göster', hideAgent: 'Ajanı Gizle',
  agents: 'Ajanlar', agentInstall: 'Kur', agentInstalling: 'Kuruluyor...', agentNotInstalled: 'Kurulu değil',
  agentFromStudio: 'Glist klasörüne kurulu', agentFromGlist: 'Glist ile geliyor',
  agentFromSystem: 'Bu bilgisayarda kurulu',
  agentInstallYourself: 'Kurulu değil. Kendi kurulum programıyla tüm bilgisayara kurulur.',
  agentsHint: 'Açık projede, Ajan sekmesinde çalışan kodlama asistanları. İstediklerinizi açın. Kurulu olmayan bir ajan buradan kurulabilir: Glist klasörüne kurulur, bilgisayarda başka hiçbir şey değişmez.',
  terminalExited: 'Kabuk kapandı, çıkış kodu:', terminalRestartHint: 'Yenisini başlatmak için bir tuşa basın.',
  initialOutput: 'Glist Studio hazır. Başlamak için bir proje açın.',
  cancel: 'İptal', create: 'Oluştur', close: 'Kapat', template: 'Şablon',
  searchProjects: 'Projelerde ara', browse: 'Göz At...', neverOpened: 'Henüz açılmadı', lastOpened: '{time} açıldı',
  noProjects: 'Burada henüz proje yok. Yeni Proje ile oluşturun ya da Göz At ile bir klasör seçin.',
  projectName: 'Proje adı', language: 'Dil', appearance: 'Görünüm',
  importTheme: 'Tema Dosyası İçe Aktar...', removeTheme: 'Kaldır',
  fonts: 'Yazı Tipleri', codeFont: 'Kod yazı tipi', codeFontSize: 'Kod boyutu', interfaceFont: 'Arayüz yazı tipi',
  systemFont: 'Sistem',
  ligatures: 'Yazı tipi destekliyorsa => gibi karakterleri birleştir',
  fontsHint: 'Listeden bir yazı tipi seçin ya da bu bilgisayarda kurulu bir yazı tipinin adını yazın.',
  pathSettings: 'PATH',
  pathHint: 'Derlemenin, çalıştırılan uygulamanın, hata ayıklayıcının ve terminalin program ve DLL aradığı klasörler, bu sırayla. Glist Studio bilgisayarın PATH’ini değil kendi listesini verir: Glist araçları, sistem klasörleri ve eklentilerin DLL’leri; bunlar burada değiştirilemez. Buradan eklenen klasörler en sona gelir.',
  pathGlist: 'Glist araçları', pathCmake: 'CMake', pathSystem: 'Bu bilgisayar', pathGit: 'Git', pathPlugin: '{name} eklentisi', pathCustom: 'Buradan eklendi',
  addPathFolder: 'Klasör Ekle...', removePathFolder: 'Kaldır', pathMissing: 'Bu klasör yok.',
  pathInvalid: 'Bu klasör eklenemez.',
  pageGeneral: 'Genel', pageAppearance: 'Görünüm', pageBuild: 'Derleme', pageRun: 'Çalıştır ve Hata Ayıkla',
  pageEnvironment: 'Ortam', pageGit: 'Git', pageAgents: 'Ajanlar', pageAbout: 'Hakkında',
  macServices: 'Servisler', macHide: 'Glist Studio’yu Gizle', macHideOthers: 'Diğerlerini Gizle', macShowAll: 'Tümünü Göster',
  macQuit: 'Glist Studio’dan Çık', macWindow: 'Pencere', selectAll: 'Tümünü Seç',
  aboutMenu: 'Glist Studio Hakkında', aboutVersion: 'Sürüm', aboutCommit: 'Commit', aboutBranch: 'Dal', aboutFolder: 'Klasör',
  aboutNoBranch: 'Yok, bir commit açık', aboutNotGit: 'Git deposu değil', aboutNotFound: 'Bulunamadı',
  aboutUnknown: 'Bilinmiyor', aboutPlugins: 'Açık projenin eklentileri', aboutSystem: 'Sistem', aboutCopy: 'Tümünü Kopyala',
  aboutCopied: 'Panoya kopyalandı.', aboutHint: 'Bir sorun bildirirken Tümünü Kopyala\'ya basın ve bildirime yapıştırın.',
  runSettings: 'Çalıştırma', runArguments: 'Program argümanları',
  runArgumentsHint: 'Çalıştır ya da Hata Ayıkla {project} programını başlatırken verilir. Boşluk içeren bir argüman tırnak içine yazılır.',
  runArgumentsNoProject: 'Programına argüman vermek için bir proje açın.',
  envSettings: 'Ortam Değişkenleri', envName: 'Ad', envValue: 'Değer', addVariable: 'Değişken Ekle',
  envHint: 'Tüm projelerde derleme, çalıştırılan uygulama, hata ayıklayıcı ve terminal için ayarlanır. PATH’in yukarıda kendi listesi var.',
  envInvalid: 'Ad harf, rakam ve alt çizgiden oluşur ve rakamla başlamaz. PATH’in yukarıda kendi listesi var.',
  themeImportFailed: 'Bu dosya bir VS Code renk teması değil.',
  languageHint: 'Arayüz dili hemen değişir.',
  editorLanguageRestart: 'Düzenleyicinin arama kutusu ve paletteki kendi komutları, Glist Studio yeniden başladığında dil değiştirir.',
  themeHint: 'Temalar tüm arayüzü renklendirir. VS Code renk temaları (.json) içe aktarılabilir.',
  undo: 'Geri Al', redo: 'Yinele', find: 'Bul', showExplorer: 'Gezgini Göster', hideExplorer: 'Gezgini Gizle',
  showOutput: 'Çıktıyı Göster', hideOutput: 'Çıktıyı Gizle', showTerminal: 'Terminali Göster', hideTerminal: 'Terminali Gizle', engineAbout: 'Glist Engine Hakkında',
  installGlist: 'Glist Engine’i Kur', installGlistMenu: 'Glist Engine’i Kur...', tryAgain: 'Yeniden Dene', stopInstall: 'Durdur',
  checkForUpdates: 'Güncellemeleri Denetle...', updateSettings: 'Güncellemeler', autoUpdate: 'Yeni sürümleri otomatik indir',
  autoUpdateHint: 'Yeni sürümler Glist Studio’nun GitHub’daki yayınlarından gelir. İndirilen sürüm, Glist Studio yeniden başladığında kurulur.',
  updatePreviews: 'Önizlemeleri de al', updatePreviewsHint: 'Önizlemeler, Glist Studio’daki her değişiklikten sürümden önce derlenir: en yeni çalışma, daha az denenmiş.',
  updateReady: 'Glist Studio {version} kurulmaya hazır.', restartToUpdate: 'Yeniden Başlat ve Güncelle',
  updateAvailable: 'Glist Studio {version} çıktı.', updateDownload: 'İndir', upToDate: 'Glist Studio güncel.',
  updateDownloading: 'Glist Studio {version} indiriliyor...', updateFailed: 'Güncellemeler denetlenemedi',
  openGlistApp: 'GlistApp’i Aç', glistMissing: 'Glist Engine bu bilgisayarda henüz kurulu değil.',
  glistInstallIntro: 'Glist Engine’in kendi kurulum programının güncel sürümünü (github.com/GlistEngine/InstallScripts) çalıştırır. Glist’in ihtiyaç duyduğu derleyicileri ve kütüphaneleri kurar; motoru, örnek bir uygulamayı ve Glist araçlarını bu klasöre koyar. 1-2 GB indirir.',
  installPasswordSystem: 'Bilgisayarın parolası gerekirse sistem bunu kendi penceresinde sorar; Glist Studio parolayı görmez.',
  installPasswordTerminal: 'Bilgisayarın parolası gerekirse aşağıda açılan terminale yazın.',
  installStep: 'Adım {step}/{total}: {name}', installStarting: 'Kurulum programı başlatılıyor...',
  glistInstalled: 'Glist Engine kuruldu.', glistInstallFailed: 'Kurulum durdu', exitCode: 'çıkış kodu',
  installStopped: 'durduruldu', confirmStopInstall: 'Kurulum durdurulsun mu? Şimdiye kadar yapılanlar korunur; yeniden kurduğunuzda kaldığı yerden devam eder.',
  layout: 'Yerleşim', zoom: 'Yakınlaştırma', preferences: 'Tercihler',
  zoomIn: 'Yakınlaştır', zoomOut: 'Uzaklaştır', resetZoom: 'Yakınlaştırmayı Sıfırla',
  scale: 'Ölçek', scaleReset: '%100’e Dön', zoomInTitle: 'Yakınlaştır (Ctrl++)', zoomOutTitle: 'Uzaklaştır (Ctrl+-)',
  resetZoomTitle: '%100’e Dön (Ctrl+0)',
  scaleHint: 'Arayüzdeki her şeyi büyütür ya da küçültür; örneğin sınıfta projeksiyonla gösterirken.',
  fileName: 'Dosya adı', folderName: 'Klasör adı', className: 'Sınıf adı', newName: 'Yeni ad',
  openedProject: 'Proje', noCmake: 'Bu klasörde CMakeLists.txt bulunamadı.',
  fileCreated: 'Dosya oluşturuldu', folderCreated: 'Klasör oluşturuldu', classCreated: 'C++ sınıfı oluşturuldu',
  projectCreated: 'Proje oluşturuldu', movedToTrash: 'Geri Dönüşüm Kutusu’na taşındı', renamed: 'Yeniden adlandırıldı',
  renamedTo: '{from} artık {to}', goToError: 'Hataya Git',
  createFailed: 'Öğe oluşturulamadı', deleteFailed: 'Öğe silinemedi', renameFailed: 'Öğe yeniden adlandırılamadı',
  fileOpenFailed: 'Dosya açılamadı', projectOpenFailed: 'Proje açılamadı', treeFailed: 'Dosyalar yüklenemedi', saveFailed: 'Kaydedilemedi',
  saved: 'kaydedildi', buildSucceeded: 'Derleme başarılı', buildFailed: 'Derleme başarısız',
  running: 'Uygulama çalışıyor', exit: 'Çıkış',
  confirmProjectSwitch: 'Kaydedilmemiş dosyalar var. Başka bir proje açılsın mı?',
  confirmClose: 'kaydedilmedi. Yine de kapatılsın mı?',
  confirmDeleteFile: 'Bu dosya Geri Dönüşüm Kutusu’na taşınsın mı?',
  confirmDeleteFolder: 'Bu klasör ve içindekiler Geri Dönüşüm Kutusu’na taşınsın mı?',
  confirmDirtyDelete: 'Bu öğedeki kaydedilmemiş değişiklikler kaybolacak. Devam edilsin mi?',
  classLocation: 'C++ sınıfı için bir klasör seçin.',
  open: 'Aç',
  readOnly: 'Salt okunur', switchSourceHeader: 'Başlık/Kaynak Dosyasına Geç', clangdRunning: 'çalışıyor',
  closeOthers: 'Diğerlerini Kapat', closeAll: 'Tümünü Kapat', splitRight: 'Sağda da Aç', splitLeft: 'Solda da Aç',
  moveRight: 'Sağ Tarafa Taşı', moveLeft: 'Sol Tarafa Taşı', splitEditor: 'Sağda da Aç',
  goToDefinition: 'Tanıma Git', goToDeclaration: 'Bildirime Git', goToReferences: 'Kullanıldığı Yerlere Git',
  goToSymbol: 'Sembole Git...', peek: 'Önizle', peekDefinition: 'Tanımı Önizle', peekDeclaration: 'Bildirimi Önizle',
  peekReferences: 'Kullanıldığı Yerleri Önizle', renameSymbol: 'Sembolü Yeniden Adlandır', changeAllOccurrences: 'Tüm Geçtiği Yerleri Değiştir',
  formatDocument: 'Belgeyi Biçimlendir', formatSelection: 'Seçimi Biçimlendir', cut: 'Kes',
  commandPalette: 'Komut Paleti', paletteSearch: 'Bir komut yazın', paletteEmpty: 'Eşleşen komut yok.', editorCommands: 'Düzenleyici',
  renameUnavailable: 'Bu sembol yeniden adlandırılamaz.',
  editOutsideProject: 'Değişiklik proje dışındaki dosyaları da etkilediği için uygulanmadı.',
  debug: 'Hata Ayıkla', debugTitle: 'Hata Ayıkla (F6)', debugView: 'Çalıştır ve Hata Ayıkla',
  startDebugging: 'Hata Ayıklamayı Başlat',
  continue: 'Devam Et', continueTitle: 'Devam Et (F5)', pause: 'Duraklat',
  stepOver: 'Üzerinden Geç', stepOverTitle: 'Üzerinden Geç (F10)', stepInto: 'İçine Gir', stepIntoTitle: 'İçine Gir (F11)',
  stepOut: 'Dışına Çık', stepOutTitle: 'Dışına Çık (Shift+F11)', toggleBreakpoint: 'Kesme Noktası Ekle/Kaldır',
  breakpoint: 'Kesme noktası', removeBreakpoint: 'Kesme noktasını kaldır',
  runAndDebug: 'ÇALIŞTIR VE HATA AYIKLA', variables: 'DEĞİŞKENLER', callStack: 'ÇAĞRI YIĞINI', breakpoints: 'KESME NOKTALARI',
  noBreakpoints: 'Hata ayıklarken orada durmak için bir satır numarasının soluna tıklayın.',
  debugIdle: 'Hata ayıklamada uygulamanız çalışırken onu duraklatabilir, değişkenlerine bakabilir ve satır satır ilerleyebilirsiniz.',
  debugStarting: 'Hata ayıklama için derleniyor ve hata ayıklayıcı başlatılıyor...',
  debugRunning: 'Çalışıyor', debugPaused: 'Duraklatıldı',
  programExited: 'Program kapandı, çıkış kodu:', debuggerFailed: 'Hata ayıklayıcı başlatılamadı',
  debuggerSettings: 'Hata Ayıklayıcı', installDebugger: 'GDB’yi Kur',
  debuggerInstalledText: 'Hata ayıklama için MSYS2’den {name} {version} kurulu.',
  debuggerNotInstalled: 'Glist araçlarında Windows için hata ayıklayıcı yok. Glist Studio, Glist derleyicilerinin kaynağı olan MSYS2’den {name} kurabilir; her dosya sabitlenmiş bir sağlama toplamıyla denetlenir ({size}).',
  installingDebugger: 'GDB kuruluyor... %{percent}', debuggerReady: 'GDB kuruldu. Başlatmak için Hata Ayıkla’ya basın.',
  debuggerInstallFailed: 'GDB kurulamadı', debuggerMissingNotice: 'Henüz bir hata ayıklayıcı yok.',
  debuggerFailedNotice: 'GDB başlatılamadı. Yeniden kurmak genellikle bunu düzeltir.', installDebuggerAgain: 'GDB’yi Yeniden Kur',
  gitSettings: 'Git',
  gitEnable: 'Git araçlarını göster',
  gitHint: 'Gezginin yanına bir Commit görünümü, düzenleyicinin altına bir Git sekmesi ve başlık çubuğuna geçerli dalı ekler; değişen satırları satır numaralarının yanında işaretler. Siz kullanana kadar projeler olduğu gibi kalır.',
  gitFound: 'Git {version} kurulu.',
  gitNotFound: 'Bu bilgisayarda Git bulunamadı. git-scm.com adresinden kurup Ayarlar\'ı yeniden açın.',
  gitName: 'Adınız',
  gitEmail: 'E-posta',
  gitIdentityHint: 'Commit\'ler bu bilgilerle imzalanır; bu bilgisayardaki tüm projelerde geçerlidir.',
  gitUpdateMethod: 'Projeyi Güncelle, uzak depodaki commit\'leri şöyle alır:',
  gitUpdateMerge: 'Birleştirerek (merge)',
  gitUpdateRebase: 'Dalın kendi commit\'lerini onların üzerine taşıyarak (rebase)',
  gitProtect: 'Gönderilmiş commit\'leri koru',
  gitProtectHint: 'Gönderilmiş bir commit düzeltilemez ve korunan dallara force push yapılamaz; böylece kimse başkalarında olan geçmişi değiştiremez.',
  gitProtectedBranches: 'Korunan dallar',
  gitProtectedHint: 'Virgülle ayırın; release/* örneğindeki gibi * her metnin yerine geçer. GitHub\'ın koruduğu dallar da korunur.',
  amendLocked: 'Son commit zaten gönderildiği için düzeltilemez.',
  forcePushLocked: '{branch} korunduğu için üzerine yazılamaz.',
  commitView: 'COMMIT',
  commitViewTitle: 'Commit (Ctrl+K)',
  changes: 'Değişiklikler',
  unversioned: 'İzlenmeyen Dosyalar',
  mergeConflicts: 'Birleştirme Çakışmaları',
  noChanges: 'Son commit\'ten beri değişiklik yok.',
  commitMessage: 'Commit mesajı',
  commitMessageHint: 'Ne değişti, neden? (Ctrl+Enter commit eder)',
  amend: 'Son commit\'i düzelt',
  commit: 'Commit',
  commitAndPush: 'Commit Et ve Gönder...',
  rollback: 'Geri Al',
  rollbackTitle: 'İşaretli Dosyaları Geri Al',
  confirmRollback: '{count} dosya son commit\'teki hâline döndürülsün mü? Bu dosyalardaki değişiklikleriniz kaybolur. Yeni dosyalar çöpe taşınır.',
  confirmRollbackOne: '{name} son commit\'teki hâline döndürülsün mü? Dosyadaki değişiklikleriniz kaybolur.',
  showDiff: 'Farkı Göster',
  openFile: 'Dosyayı Aç',
  addToGitignore: '.gitignore\'a Ekle',
  showHistory: 'Geçmişi Göster',
  markResolved: 'Çözüldü Olarak İşaretle',
  keepMine: 'Benimkini Koru',
  takeTheirs: 'Onlarınkini Al',
  keepBoth: 'İkisini de Koru',
  conflictHint: 'Her değişikliği ayrı seçmek için dosyayı açın ya da tüm dosya için bir tarafı seçin.',
  noRepository: 'Bu proje geçmişini henüz Git ile tutmuyor.',
  noRepositoryHint: 'Bir depoyla projenin sürümlerini commit olarak kaydedebilir, istediğinize geri dönebilir ve projeyi paylaşabilirsiniz.',
  pluginsView: 'Eklentiler', pluginsTitle: 'EKLENTİLER', pluginsSearch: 'Eklentilerde ara',
  pluginsInstalled: 'Kurulu', pluginsAvailable: 'Kurulabilir',
  updateAskTitle: '{name} güncellensin mi?',
  updateAskHint: '{source} üzerinde yeni commit’ler var ve {name} içinde sizin çalışmanız var: {work}.',
  updateWorkFile: '1 değişmiş dosya', updateWorkFiles: '{count} değişmiş dosya',
  updateWorkCommit: 'size ait 1 commit', updateWorkCommits: 'size ait {count} commit', updateWorkAnd: ' ve ',
  updateKeepFiles: 'Değişikliklerimi koru: yeni commit’leri al, sonra değişmiş dosyalarımı geri koy',
  updateKeepRebase: 'Çalışmamı koru: commit’lerimi yenilerin üstüne taşı',
  updateKeepMerge: 'Çalışmamı koru: yeni commit’leri benimkilerle birleştir',
  updateKeepMergeWhy: 'Sizinkiler korumalı {branch} dalında olduğu için yeniden yazılmaz, birleştirilir.',
  updateKeepRebasePushed: 'Sizinkiler zaten {branch} dalında; bundan sonra oraya yeniden göndermek force push gerektirir.',
  updateReplace: '{source} üzerindeki sürümü kullan: commit’lerim kendi dallarında, değişmiş dosyalarım Saklananlar’da kalsın',
  updateReplaceFiles: '{source} üzerindeki sürümü kullan: değişmiş dosyalarım Saklananlar’a gitsin',
  updateReplaceCommits: '{source} üzerindeki sürümü kullan: commit’lerim kendi dallarında kalsın',
  updateButton: 'Güncelle', updateUpToDate: '{name}, {source} ile güncel.',
  updateDoneFastForward: '{name}, {source} üzerinden güncellendi.',
  updateDoneRebase: '{name}, {source} üzerinden güncellendi; commit’leriniz en üstte.',
  updateDoneMerge: '{name}, {source} üzerinden güncellendi ve commit’lerinizle birleştirildi.',
  updateDoneReplace: '{name} artık {source} üzerindeki sürümle aynı.',
  updateKeptStash: 'Değişmiş dosyalarınız Saklananlar’da, "{stash}" adıyla.', updateKeptBranch: 'Commit’leriniz {branch} dalında.',
  updateStashClash: 'Değişmiş dosyalarınız yeni sürümle çakıştığı için Git sekmesindeki Saklananlar’da bekliyor.',
  updateNothingChanged: 'Hiçbir şey değişmedi.', updateUseSource: '{source} Üzerindeki Sürümü Kullan', updateResolve: 'Çakışmaları Çöz',
  checkoutUpdateFailed: '{name} güncellenemedi', updatesNotice: '{names} için yeni sürüm var',
  dependenciesUpToDate: 'Güncel: {names}',
  installPlugin: 'Kur', updatePlugin: 'Güncelle', addToProject: 'Projeye Ekle', removeFromProject: 'Projeden Çıkar',
  installPluginTitle: 'glistplugins içine kur', updatePluginTitle: '{source} üzerinden güncelle',
  pluginAdd: 'Ekle', pluginAdded: 'Eklendi', pluginRemove: 'Çıkar',
  pluginBehind: '{source} üzerinde {count} yeni', pluginNotOfficial: '{source} kaynaklı değil',
  pluginOtherBranch: '{branch} dalında', pluginChanged: 'Sizin değişiklikleriniz var', pluginWorking: 'Çalışıyor...',
  pluginInstalled: '{name}, glistplugins içine kuruldu.', pluginInstallFailed: '{name} kurulamadı',
  pluginUseFailed: '{name} projeye eklenemedi',



  pluginFrom: 'Kaynak: {source}',
  pluginsNeedGit: 'Eklentileri kurmak ve güncellemek için Git gerekiyor. git-scm.com adresinden kurabilirsiniz.',
  pluginsListFailed: 'GlistPlugins’e ulaşılamadı',
  createRepository: 'Git Deposu Oluştur',
  gitNoProject: 'Değişikliklerini görmek için bir proje açın.',
  gitMissing: 'Bu bilgisayarda Git bulunamadı. git-scm.com adresinden kurabilirsiniz.',
  repositoryAt: 'Depo: {location}',
  merging: 'Birleştiriliyor: {subject}',
  rebasing: 'Rebase yapılıyor: {subject}',
  cherryPicking: 'Cherry-pick yapılıyor: {subject}',
  reverting: 'Geri alınıyor: {subject}',
  resolveThenCommit: 'Çakışmaları çözün, sonra commit edin.',
  resolveThenContinue: 'Çakışmaları çözün, sonra devam edin.',
  abort: 'Vazgeç',
  skip: 'Atla',
  updateProject: 'Projeyi Güncelle',
  updateProjectTitle: 'Projeyi Güncelle (Ctrl+T)',
  push: 'Gönder...',
  pushTitle: 'Gönder (Ctrl+Shift+K)',
  fetch: 'Getir',
  committedMessage: 'Commit edildi: {subject}',
  stateModified: 'Değiştirildi',
  stateAdded: 'Eklendi',
  stateDeleted: 'Silindi',
  stateRenamed: 'Yeniden adlandırıldı',
  stateUntracked: 'İzlenmiyor',
  stateConflict: 'Çakışma',
  stateTypechange: 'Türü değişti',
  stateIgnored: 'Git yok sayıyor',
  diffHead: 'Son commit ({hash})',
  diffWorking: 'Sizin sürümünüz',
  diffCommit: 'Commit {hash}',
  diffMissing: 'Bu sürümde yok',
  diffBinary: 'Bu dosya metin olmadığı için karşılaştırılacak satır yok.',
  diffTooLarge: 'Bu dosya karşılaştırılamayacak kadar büyük.',
  previousChange: 'Önceki Değişiklik',
  nextChange: 'Sonraki Değişiklik',
  toggleSideBySide: 'Yan Yana veya Tek Sütun',
  gitTab: 'GIT',
  gitLog: 'Geçmiş',
  gitBranches: 'Dallar',
  gitRemotes: 'Uzak Depolar',
  gitStashes: 'Saklananlar',
  gitConsole: 'Konsol',
  allBranches: 'Tüm dallar',
  searchCommits: 'Mesajlarda veya hash\'lerde ara',
  historyOf: '{name} geçmişi',
  clearFilter: 'Tüm geçmişi göster',
  noCommits: 'Henüz commit yok.',
  selectCommit: 'Neleri değiştirdiğini görmek için bir commit seçin.',
  copyHash: 'Revizyon Numarasını Kopyala',
  checkoutRevision: 'Bu Revizyona Geç',
  newBranch: 'Yeni Dal...',
  newTag: 'Yeni Etiket...',
  cherryPick: 'Cherry-Pick',
  revertCommit: 'Commit\'i Geri Al',
  resetHere: 'Geçerli Dalı Buraya Sıfırla...',
  resetTitle: '{branch} dalını {hash} commit\'ine sıfırla',
  resetMixed: 'Sonraki commit\'lerdeki değişiklikleri, commit edilmemiş değişiklikler olarak koru',
  resetSoft: 'Değişiklikleri, yeniden commit edilmeye hazır olarak koru',
  resetHard: 'Sonraki commit\'leri ve commit edilmemiş tüm değişiklikleri sil',
  reset: 'Sıfırla',
  confirmResetHard: 'Sonraki commit\'ler ve commit edilmemiş tüm değişiklikler silinsin mi? Bu geri alınamaz.',
  local: 'Yerel',
  remote: 'Uzak',
  tags: 'Etiketler',
  checkout: 'Geçiş Yap',
  mergeInto: '{branch} dalına birleştir',
  rebaseOnto: '{branch} dalını bunun üzerine rebase et',
  deleteBranch: 'Sil',
  currentBranch: 'geçerli',
  branchGone: 'uzak depodan silinmiş',
  confirmDeleteBranch: '{name} dalı silinsin mi?',
  confirmForceDelete: '{name} dalında başka hiçbir dalda olmayan commit\'ler var. Yine de silinsin mi? Bu commit\'ler kaybolur.',
  confirmDeleteRemoteBranch: '{name} uzak depodan silinsin mi? Onu kullanan herkes için silinir.',
  confirmDeleteTag: '{name} etiketi silinsin mi?',
  branchName: 'Dal adı',
  newBranchFrom: '{start} noktasından yeni dal',
  tagName: 'Etiket adı',
  tagMessage: 'Mesaj (isteğe bağlı)',
  addRemote: 'Uzak Depo Ekle...',
  remoteName: 'Ad',
  remoteUrl: 'Adres',
  editRemote: 'Adresi Düzenle...',
  removeRemote: 'Kaldır',
  confirmRemoveRemote: '{name} uzak deposu bu depodan kaldırılsın mı? Uzak depodaki hiçbir şey silinmez.',
  noRemotes: 'Henüz uzak depo yok. Projeyi GitHub gibi bir yere göndermek için bir tane ekleyin.',
  stashChanges: 'Değişiklikleri Sakla...',
  stashMessage: 'Mesaj (isteğe bağlı)',
  stashUntracked: 'İzlenmeyen dosyaları da ekle',
  applyStash: 'Uygula',
  popStash: 'Uygula ve Sil',
  dropStash: 'Sil',
  confirmDropStash: '{name} silinsin mi? İçindeki değişiklikler kaybolur.',
  noStashes: 'Saklanan bir şey yok. Saklamak değişikliklerinizi kenara koyar; başka bir işe geçip onları sonra geri getirebilirsiniz.',
  clearConsole: 'Konsolu Temizle',
  gitRefresh: 'Yenile',
  pushCommits: 'Commit\'leri Gönder',
  pushTarget: '{branch} dalını {remote} deposuna',
  pushNothing: 'Gönderilecek commit yok.',
  pushNewBranch: 'Dal uzak depoda yeni; bundan sonra onu takip edecek.',
  pushTags: 'Etiketleri de gönder',
  forcePush: 'Uzak dalın üzerine yaz (force push)',
  forcePushHint: 'Yalnızca gönderildikten sonra değiştirilen commit\'ler için. Başkalarının o zamandan beri gönderdiği commit\'ler kaybolur.',
  pushButton: 'Gönder',
  remoteLabel: 'Uzak depo',
  cloneMenu: 'Git\'ten Al...',
  cloneTitle: 'Git\'ten Al',
  cloneUrl: 'Depo adresi',
  cloneLocation: '{location} klasörüne kopyalanır.',
  cloneButton: 'Klonla',
  cloning: 'Klonlanıyor...',
  identityTitle: 'Commit\'i kim yapıyor?',
  identityHint: 'Git her commit\'le bir ad ve e-posta kaydeder. Bunlar bu bilgisayardaki tüm projeler için saklanır ve Ayarlar\'dan değiştirilebilir.',
  saveButton: 'Kaydet',
  menuGit: 'Git',
  commitMenu: 'Commit...',
  pushMenu: 'Gönder...',
  branchesMenu: 'Dallar...',
  gitLogMenu: 'Git Geçmişini Göster',
  remotesMenu: 'Uzak Depoları Yönet...',
  currentFile: 'Geçerli Dosya',
  annotate: 'Git Blame ile Satır Geçmişini Göster',
  hideAnnotate: 'Satır Geçmişini Kapat',
  localBranches: 'Yerel Dallar',
  remoteBranches: 'Uzak Dallar',
  manageBranches: 'Dalları Yönet...',
  detached: '{hash} commit\'inde (dal yok)',
  branchChipTitle: 'Git dalı: {branch}',
  aheadBehind: '{ahead} gönderilecek, {behind} güncellenecek',
  pushedTo: '{target} dalına gönderildi.',
  updatedFrom: '{upstream} dalından güncellendi.',
  fetched: 'Getirildi.',
  checkedOut: '{name} dalına geçildi.',
  smartCheckout: 'Saklayıp Geç',
  conflictsNotice: 'Çözülmesi gereken çakışmalar var. Commit görünümünde listelenirler.',
  showConflicts: 'Göster',
  showConsole: 'Konsolu Göster',
  deleteAnyway: 'Yine de Sil',
  gitFailed: 'Git bunu yapamadı',
  committing: 'Commit ediliyor...',
  pushing: 'Gönderiliyor...',
  updating: 'Güncelleniyor...',
  fetching: 'Getiriliyor...',
  gitWorking: 'Çalışıyor...',
  rollbackChange: 'Bu Değişikliği Geri Al',
  linesBefore: 'Bu değişiklikten önce',
  linesAdded: 'Bu satırlar son commit\'ten sonra eklendi.',
  notCommittedYet: 'Henüz commit edilmedi',
  blameUnavailable: 'Bu dosyanın henüz commit edilmiş geçmişi yok.',
  mine: 'Benimki',
  theirs: 'Onlarınki',
  showInLog: 'Git Geçmişinde Göster',
  blameClick: 'Commit\'i Git geçmişinde görmek için satır numarasına tıklayın.',
  conflictsResolvedIn: '{name} içindeki tüm çakışmalar çözüldü.',
  keptMine: '{name}: sizin sürümünüz korundu.',
  confirmShared: '{name}, onu kullanan tüm projelerde ortak; bu işlem hepsini etkiler. Devam edilsin mi?',
  engineAndPlugins: 'Motor ve Eklentiler',
  updateDependencies: 'Motoru ve Eklentileri Güncelle',
  confirmUpdateDependencies: '{names} için yayımlandıkları yerdeki son commit\'ler alınsın mı? Onları kullanan her proje bu değişiklikleri alır.',
  kindProject: 'proje',
  kindEngine: 'motor',
  kindPlugin: 'eklenti',
  repositoryChoice: 'Depo',
  pushedRepository: '{name}: {target} dalına gönderildi.',
  sharedChanges: '{name} içindeki değişiklikler, onu kullanan tüm projeleri etkiler ve kendi deposuna commit edilir.',
  sharedEdit: '{name}, onu kullanan tüm projelerde ortak; kaydettiğinizde hepsi için değişir.',
  tookTheirs: '{name}: onların sürümü alındı.',
  buildSettings: 'Derleme',
  autoConfigure: 'CMake dosyaları değişince yeniden yapılandır',
  autoConfigureHint: 'Projede, motorda ya da eklentilerde bir CMake dosyası değişince CMake projeyi kısa süre sonra yeniden yapılandırır; böylece kod tamamlama yeni dosyaları derlemeden tanır.',
  showTargets: 'Tüm hedefleri göster',
  showTargetsHint: 'Çalıştır\'ın yanına, motorunkiler ve eklentilerinkiler dahil, CMake\'in derlediği tüm hedeflerin listesini ekler; CLion\'daki gibi. Derle, Çalıştır ve Hata Ayıkla seçilen hedefi kullanır.',
  targetChoice: 'Derlenip çalıştırılacak hedef', targetLibrary: 'kütüphane', targetStep: 'derleme adımı',
  noTargets: 'Henüz hedef yok: bir kez derleyin', otherTargets: 'Diğer',
};

const dictionaries = { en, tr };

type Wording = Partial<Record<TranslationKey, string>>;

// Names the host gives its trash, file manager and terminal; the dictionaries
// above use the Windows ones.
const hostWording: Record<string, Record<Language, Wording>> = {
  darwin: {
    en: {
      delete: 'Move to Trash', deleteTitle: 'Move Selected Item to Trash', movedToTrash: 'Moved to Trash',
      confirmDeleteFile: 'Move this file to the Trash?',
      confirmDeleteFolder: 'Move this folder and all its contents to the Trash?',
      systemExplorer: 'Finder', commandPrompt: 'Terminal',
    },
    tr: {
      delete: 'Çöp Sepeti’ne Taşı', deleteTitle: 'Seçili Öğeyi Çöp Sepeti’ne Taşı', movedToTrash: 'Çöp Sepeti’ne taşındı',
      confirmDeleteFile: 'Bu dosya Çöp Sepeti’ne taşınsın mı?',
      confirmDeleteFolder: 'Bu klasör ve içindekiler Çöp Sepeti’ne taşınsın mı?',
      systemExplorer: 'Finder', commandPrompt: 'Terminal',
    },
  },
  linux: {
    en: {
      delete: 'Move to Trash', deleteTitle: 'Move Selected Item to Trash', movedToTrash: 'Moved to Trash',
      confirmDeleteFile: 'Move this file to the Trash?',
      confirmDeleteFolder: 'Move this folder and all its contents to the Trash?',
      systemExplorer: 'File Manager', commandPrompt: 'Terminal',
    },
    tr: {
      delete: 'Çöp Kutusu’na Taşı', deleteTitle: 'Seçili Öğeyi Çöp Kutusu’na Taşı', movedToTrash: 'Çöp Kutusu’na taşındı',
      confirmDeleteFile: 'Bu dosya Çöp Kutusu’na taşınsın mı?',
      confirmDeleteFolder: 'Bu klasör ve içindekiler Çöp Kutusu’na taşınsın mı?',
      systemExplorer: 'Dosya Yöneticisi', commandPrompt: 'Terminal',
    },
  },
};

export const savedLanguage = (): Language => {
  try { return window.localStorage.getItem('glist-studio-language') === 'tr' ? 'tr' : 'en'; }
  catch { return 'en'; }
};

let language: Language = savedLanguage();

export const getLanguage = (): Language => language;
export const t = (key: TranslationKey): string =>
  hostWording[getHostPlatform()]?.[language][key] ?? dictionaries[language][key];

export const applyLanguage = (next: Language): void => {
  language = next;
  try { window.localStorage.setItem('glist-studio-language', next); } catch { /* Storage may be unavailable. */ }
  document.documentElement.lang = next;
  document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((node) => {
    const key = node.dataset.i18n as TranslationKey;
    if (key in en) node.textContent = t(key);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-title]').forEach((node) => {
    const key = node.dataset.i18nTitle as TranslationKey;
    if (key in en) node.title = shortcutLabel(t(key));
  });
  document.querySelectorAll<HTMLInputElement>('[data-i18n-placeholder]').forEach((node) => {
    const key = node.dataset.i18nPlaceholder as TranslationKey;
    if (key in en) node.placeholder = t(key);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-aria-label]').forEach((node) => {
    const key = node.dataset.i18nAriaLabel as TranslationKey;
    if (key in en) node.setAttribute('aria-label', t(key));
  });
  document.querySelectorAll('kbd').forEach((node) => { node.textContent = shortcutLabel(node.textContent ?? ''); });
};
